# AGREGAR Y QUITAR COLUMNAS
#
# ALTER TABLE <nombre_tabla>
# ADD COLUMN <nombre_columna_nueva> <tipo_de_datos>(tamaño);
#
# ALTER TABLE <nombre_tabla>
# DROP COLUMN <nombre_columna_nueva>;
#
#\\\\\\ DESARROLLO \\\\\\

USE SAKILA;

CREATE TABLE KOI
SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM ADDRESS;

SELECT * FROM KOI;

ALTER TABLE KOI
DROP COLUMN DISTRICT;

SELECT * FROM KOI;

ALTER TABLE KOI
ADD COLUMN NEW_DISTRICT VARCHAR(20);

SELECT * FROM KOI;