# TRUNCAR UNA TABLA
#
# TRUNCATE TABLE <nombre_table>
#
# \\\\\ DESARROLLO \\\\\
USE SAKILA;

CREATE TABLE KOI
SELECT CITY_ID, PHONE, DISTRICT, LOCATION FROM ADDRESS;

SELECT * FROM KOI;

TRUNCATE TABLE KOI;

SELECT *FROM KOI;