# CAMBIAR EL DATATYPE DE UNA COLUMNA
#
# ALTER TABLE <NOMBRE_TABLA>
# MODIFY <nombre_columna> <tipo_de_dato_nuevo>;
#
#\\\\\ DESARROLLO \\\\\

USE GRUPOS;

DESC GRUPO_1;

ALTER TABLE GRUPO_1
MODIFY DIR_COD VARCHAR(20);

DESC GRUPO_1;

ALTER TABLE GRUPO_1
MODIFY DIR_COD INT;

DESC GRUPO_1;