# Ejercicio
# Parte 1
# Crear 3 tablas con la estructura:
## MASCOTAS:
### Campos: ID, NOMBRE, ID_DUEÑO, SERVICIO
## PERSONA:
### Campos: ID, NOMBRE, APELLIDO, COD_ZIP, TLF
## DIRECCIONES
### Campos: ZIP, NOMBRE_ZONA, RUTA

# Parte 2
#
# Agregar una PK al campo ID en las tablas Mascotas y Personas.
# Agregar una FK al campo ID_DUEÑO en la tabla Mascotas que referencie al campo ID en la tabla Personas.
# Agrega una columna llamada EMAIL a la tabla Personas.
# Agrega una UNIQUE CONSTRAINT  a la columna EMAIL de la tabla personas.
# Cambia el nombre a la columna NOMBRE de la tabla Mascotas por PRIMER_NOMBRE.
# Cambia el tipo de dato a la columna RUTA en la tabla de Direcciones por CHAR(12).

#\\\\\ DESARROLLO \\\\\
# Parte 1

CREATE DATABASE EJERCICIO_1;
USE EJERCICIO_1;

CREATE TABLE MASCOTAS (
ID INT NOT NULL,
NOMBRE VARCHAR(20),
ID_DUEÑO INT NOT NULL,
SERVICIO VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE PERSONAS (
ID INT NOT NULL,
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
COD_ZIP INT NOT NULL,
TLF INT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE DIRECCIONES (
ZIP INT NOT NULL,
NOMBRE_ZONA VARCHAR(20),
RUTA VARCHAR(20)
);

# Parte 2

ALTER TABLE MASCOTAS
ADD CONSTRAINT FK_PERSONASID
FOREIGN KEY (ID_DUEÑO) REFERENCES PERSONAS(ID);

ALTER TABLE PERSONAS
ADD CONSTRAINT FK_ZIP
FOREIGN KEY (COD_ZIP) REFERENCES DIRECCIONES(ZIP);

ALTER TABLE PERSONAS
ADD COLUMN EMAIL VARCHAR(20);

ALTER TABLE PERSONAS
ADD CONSTRAINT U_EMAIL UNIQUE (EMAIL);

ALTER TABLE MASCOTAS
CHANGE NOMBRE PRIMER_NOMBRE VARCHAR(20);

ALTER TABLE DIRECCIONES
MODIFY RUTA CHAR(12);

DESC MASCOTAS;
DESC PERSONAS;
DESC DIRECCIONES;






