CREATE DATABASE BODEGA;

USE BODEGA;

CREATE TABLE PRODUCTOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(28),
PRECIO FLOAT,
PROVEEDOR VARCHAR(28)
);

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROVEEDOR)
VALUES
	('Café', 405, 'Dolca');
    
SELECT * FROM PRODUCTOS;

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROVEEDOR)
VALUES
	('Harina 0000', 83.20, 'Pureza'),
    ('Gaseosa', 199.05, 'Coca-Cola');
    
ALTER TABLE PRODUCTOS
CHANGE PROVEEDOR MARCA VARCHAR(28);

SELECT * FROM PRODUCTOS;