# COMO BORRAR DATOS EN UNA TABLA
#
#\\\\\ DESARROLLO \\\\\

USE BODEGA;

CREATE TABLE PERSONAS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20),
EDAD INT NOT NULL,
PAIS VARCHAR(20)
);

SELECT * FROM PERSONAS;

INSERT INTO PERSONAS (NOMBRE, EDAD, PAIS)
VALUES
	('Gonzalo', 27, 'Argentina'),
    ('María', 35, 'Chile'),
    ('Juan', 24, 'Uruguay'),
    ('Antonia', 40, 'Paraguay'),
    ('Julio', 22, 'Perú');

SELECT * FROM PERSONAS;

# ELIMINAR UNA FILA

DELETE FROM PERSONAS
WHERE NOMBRE = 'Gonzalo';

# ELIMINAR TODAS LAS FILAS

DELETE FROM PERSONAS;
SELECT * FROM PERSONAS;