# CREAR TABLA DE PELICULAS
#
#\\\\\ DESARROLLO \\\\\

SHOW DATABASES;
CREATE DATABASE SIS_RESERVACIONES;

USE SIS_RESERVACIONES;

CREATE TABLE PELICULAS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL UNIQUE,
DUR_MIN INT NOT NULL
);


SHOW TABLES;