# CREAR TABLA DE CLIENTES
#
#\\\\\ DESARROLLO \\\\\

USE SIS_RESERVACIONES;

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL UNIQUE
);


SHOW TABLES;