# CREAR TABLA DE CLIENTES
#
#\\\\\ DESARROLLO \\\\\

USE SIS_RESERVACIONES;

CREATE TABLE FUNCIONES (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PELICULA INT NOT NULL,
ID_SALA INT NOT NULL,
HORA_INICIO DATETIME NOT NULL,
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULAS(ID),
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);


SHOW TABLES;