# CREAR TABLA DE ASIENTOS RESERVADOS
#
#\\\\\ DESARROLLO \\\\\

USE SIS_RESERVACIONES;

CREATE TABLE ASIENTOS_RESERVADOS (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_RESERVACION INT NOT NULL,
ID_ASIENTO INT NOT NULL,
FOREIGN KEY (ID_RESERVACION) REFERENCES RESERVACIONES(ID),
FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTOS(ID)
);


SHOW TABLES;